### PR TITLE
Fix missing shading

### PR DESCRIPTION
**Pull request by sgdc3**

### CODE REVIEW

**Comment by sgdc3** [comment]
Github seems to be broken.... i select my repo but it continues sending the pr to your, sorry.

**Comment by sgdc3** [comment]
A page refresh fixed the issue, sorry again xD

**Comment by RoboMWM** [comment]
idk what you're doing but if you're trying to make this 1.8.8 compatible, the upstream version works with that.

**Comment by sgdc3** [comment]
I added some features for my server ;)

**Comment by RoboMWM** [comment]
Lol ok, all I did was have it execute a command and update to 1.9 protocollib, seems you just added a configurable command instead? And also a way to check everyone at once I suppose. Either way probably would've been better to fork the upstream instead of my trial-and-error commits :P

**Comment by sgdc3** [comment]
@RoboMWM no, it's fine ;)

**Comment by RoboMWM** [comment]
ayyy, mind PR'ing your 1.10 fixes (if possible, idk how to cherry-pick and merge specific commits)? Also, seems the upstream repo has updated to 1.9, don't know if that includes 1.10 fixes though.

That, or if you could let me know if it's safe to use your version?

**Comment by sgdc3** [comment]
1.10 is the right branch

**Comment by sgdc3** [comment]
and yes, it works fine ;)

**Comment by sgdc3** [comment]
P S: haven't tested 1.11 yet

**Pull request closed without merging**
